apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ssahibsingh/rf-file-server-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: backendUrl

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  backendUrl: aHR0cDovL2xvY2FsaG9zdDo4MDAwL2FwaQ==
