name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rf-file-server-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rf-file-server-backend:latest ./backend

          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/rf-file-server-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rf-file-server-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Azure VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

          scp -i private-key.pem ./azure-deployment/ azureuser@20.204.47.49:~/rfCode/
          ssh -i private-key.pem azureuser@20.204.47.49 "cd ~/rfCode/azure-deployment && kubectl apply -f frontend-deployment.yaml && kubectl apply -f backend-deployment.yaml"
